//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArendaProject.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rent
    {
        public int idRent { get; set; }
        public int idEmployee { get; set; }
        public int idClient { get; set; }
        public int idInstrument { get; set; }
        public System.DateTime TimeRentStart { get; set; }
        public System.DateTime TimeRentEnd { get; set; }
        public decimal Price { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Instrument Instrument { get; set; }
    }
}
